---
name: run_tests

on:
  workflow_dispatch:
  workflow_call:

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install muffet
        env:
          URL: TomWright/dasel
          GREP_SCHEME: "_linux_amd64"
          TARGET_FOLDER: /home/.local/bin
        run: |
          sudo mkdir -p ${TARGET_FOLDER}
          curl https://raw.githubusercontent.com/triole/ghwfe/master/sh/install_from_github.sh | bash
          mv /home/.local/bin/dasel* /home/.local/bin/dasel
          chmod +x /home/.local/bin/dasel
      - name: validate _data files
        env:
          PATH: /bin:/sbin:/usr/bin:/usr/sbin:/home/.local/bin
        run: .github/sh/validate_data_files.sh
